// flow-typed signature: ac1ceaa46b1f3178aeead2a7e365558d
// flow-typed version: <<STUB>>/es6-object-assign_v^1.1.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es6-object-assign'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'es6-object-assign' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'es6-object-assign/auto' {
  declare module.exports: any;
}

declare module 'es6-object-assign/dist/object-assign-auto' {
  declare module.exports: any;
}

declare module 'es6-object-assign/dist/object-assign-auto.min' {
  declare module.exports: any;
}

declare module 'es6-object-assign/dist/object-assign' {
  declare module.exports: any;
}

declare module 'es6-object-assign/dist/object-assign.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'es6-object-assign/auto.js' {
  declare module.exports: $Exports<'es6-object-assign/auto'>;
}
declare module 'es6-object-assign/dist/object-assign-auto.js' {
  declare module.exports: $Exports<'es6-object-assign/dist/object-assign-auto'>;
}
declare module 'es6-object-assign/dist/object-assign-auto.min.js' {
  declare module.exports: $Exports<'es6-object-assign/dist/object-assign-auto.min'>;
}
declare module 'es6-object-assign/dist/object-assign.js' {
  declare module.exports: $Exports<'es6-object-assign/dist/object-assign'>;
}
declare module 'es6-object-assign/dist/object-assign.min.js' {
  declare module.exports: $Exports<'es6-object-assign/dist/object-assign.min'>;
}
declare module 'es6-object-assign/index' {
  declare module.exports: $Exports<'es6-object-assign'>;
}
declare module 'es6-object-assign/index.js' {
  declare module.exports: $Exports<'es6-object-assign'>;
}
